version: "3.8"

services:
  cs-commsult-app:
    image: commsult/composedemo
    volumes:
    - "./config:/usr/src/myapp/config"
    environment:
      SPRING_CONFIG_NAME: application
      SPRING_CONFIG_LOCATION: file:./config/
    ports:
      #we map the host port of 18091 to connect to the port 8091 of the container's port
      - 18091:8091
    entrypoint: ["java", "-jar", "compose-demo.jar"]
    healthcheck:
      test: echo $$(wget -q - http://0.0.0.0:8091/actuator/health 2>&1 | grep -o -q "UP" || exit
      start_period: 5s
      interval: 5s
      retries: 5

  cs-compose-db:
    image: postgres:14.5-alpine
    container_name: cs-compose-db
    ports:
    - 35433:5432
    volumes:
    - cs-compose-db-data:/var/lib/postgresql/data
    logging:
      options:
        max-size: 10m
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: docker-workshop
    command: ["postgres", "-c", "log_statement=all"]
    healthcheck:
      test: pg_isready -U docker -d docker-workshop && echo "1" || echo "0" 
      interval: 5s

volumes:
  cs-compose-db-data: